name: Label pull requests

on:
  - pull_request

jobs:
  label:
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
